### ISSUE TITLE
Beta Version Todo List

### ISSUE THREAD

**Issue by hzz780** [hzz780/aelf-web-extension#2]
- [X] Wallet operation: create, unlock, lock, check, update, clear. 【done】

- [X] Keypair operation: create(must backup at first, after backup, import it), backup, remove,get. 【done】

- [X] Keypari permissions: setPermission, checkPermission, removePermisson. 【done】19.01.14

- [ ] history: insert, get 【half day】

- [X] Contract: checkPermission->ContractAt, instance of DAPPs.【a day,】【done】19.01.16, 1.5day actually

- [x] Page call Extension Fns demo & test 【a day】19.01.18

- [x] Demo & API docs 【a day】【50%】

**Comment by hzz780** [comment]
history move to next version.
